sudo: false
language: node_js
node_js:
  - "12"
notifications:
  disabled: true
services:
  - docker

env:
  secure: ...

install:
  - npm ci
  - npm run bootstrap
cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master
