sudo: false
language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - curl https://cli-assets.heroku.com/install.sh | sh

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run build
  - npm run test

# deploy:
#   skip_cleanup: true
#   provider: script
#   strategy: bash scripts/deploy.sh
#   on:
#     branch: master
