sudo: false
language: node_js
node_js:
  - "12"
services:
  - docker
install:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
