sudo: false
language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - curl https://cli-assets.heroku.com/install.sh | sh

install:
  - npm ci

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    strategy: ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
