sudo: false
language: node_js
node_js:
  - "12"
services:
  - docker

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    strategy: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
